const p=window.PORTFOLIO,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes=[['index.html','หน้าปก'],['preface.html','คำนำ'],['profile.html','ประวัติส่วนตัว'],['experience.html','ประสบการณ์'],['thanks.html','THANK YOU']];
const current=location.pathname.split('/').pop()||'index.html',page=Math.max(0,routes.findIndex(r=>r[0]===current));
const photo=`<img class="portrait" src="${esc(p.portrait)}" alt="รูปของ ${esc(p.name)}">`;
const nav=routes.map(([url,label],i)=>`<a href="${url}" ${i===page?'aria-current="page"':''}><span>0${i+1}</span>${label}</a>`).join('');
const controls=`${page>0?`<a class="button secondary" href="${routes[page-1][0]}">← ย้อนกลับ</a>`:'<span></span>'}${page<routes.length-1?`<a class="button" href="${routes[page+1][0]}">หน้าถัดไป →</a>`:`<a class="button" href="index.html">กลับหน้าแรก ↗</a>`}`;
const pages=[
`<section class="cover-page"><div class="cover-copy"><p class="kicker">PORTFOLIO · 2026</p><h1>${esc(p.name)}</h1><p class="cover-role">แฟ้มสะสมผลงาน<br><span>คณะพาณิชยศาสตร์และการบัญชี</span></p><div class="cover-school"><img src="assets/TU.png" alt="มหาวิทยาลัยธรรมศาสตร์"><div><strong>มหาวิทยาลัยธรรมศาสตร์</strong><span>Thammasat University</span></div></div><div class="cover-details"><span>คณะ</span><strong>คณะพาณิชยศาสตร์และการบัญชี<br>มหาวิทยาลัยธรรมศาสตร์</strong><span>สาขา</span><strong>สาขาวิชาการจัดการธุรกิจแบบบูรณาการ<br><em>(Integrated Business Administration)</em></strong><span>โรงเรียน</span><strong class="school-lockup"><img src="assets/BUU.jpg" alt="โลโก้โรงเรียน BUU">โรงเรียนบ้านบึง“อุตสาหกรรมนุเคราะห์”</strong></div></div><div class="cover-photo">${photo}<div class="photo-ring"></div><span class="vertical-label">INTEGRATED BUSINESS ADMINISTRATION</span></div></section>`,
`<section class="content-page narrow"><div class="page-mark">02 / PREFACE</div><h1>คำนำ</h1><div class="rule"></div><div class="prose">${p.introduction.map(x=>`<p>${esc(x)}</p>`).join('')}</div></section>`,
`<section class="content-page"><div class="page-mark">03 / ABOUT ME</div><div class="profile-grid"><div><h1>ประวัติ<br><span>ส่วนตัว</span></h1>${photo}<div class="mini-name">${esc(p.name)}<br><small>${esc(p.nickname)}</small></div></div><div class="profile-info"><div class="info-list">${p.facts.map(([k,v])=>`<div><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`).join('')}</div><h2>ความสามารถพิเศษ</h2><ul class="skills">${p.skills.map(s=>`<li>${esc(s)}</li>`).join('')}</ul></div></div></section>`,
`<section class="content-page"><div class="page-mark">04 / EXPERIENCE</div><h1>ประสบการณ์</h1><p class="lead">ประสบการณ์ที่หล่อหลอมความรับผิดชอบ การสื่อสาร และการทำงานร่วมกับผู้อื่น</p><div class="experience-grid">${p.experiences.map((x,i)=>`<article class="experience-card"><div class="experience-image"><span>0${i+1}</span></div><div><h2>${esc(x.title)}</h2><p>${esc(x.description)}</p></div></article>`).join('')}</div></section>`,
`<section class="thanks-page"><p class="kicker">05 / THE END</p><h1>THANK<br><span>YOU</span></h1><div class="thanks-copy"><p>${esc(p.thanks[0])}</p><p class="quote">“${esc(p.thanks[1])}”</p><p>${esc(p.thanks[2])}<br>${esc(p.thanks[3])}</p></div><a class="text-link" href="index.html">กลับสู่หน้าปก ↗</a></section>`];
document.title=`${routes[page][1]} · ${p.name}`;
document.querySelector('#app').innerHTML=`<header class="site-header"><a class="brand" href="index.html">PORTFOLIO</a><nav>${nav}</nav><div class="header-count">${String(page+1).padStart(2,'0')} / 05</div></header><main>${pages[page]}<div class="page-controls">${controls}</div></main><footer><span>${esc(p.name)} · Portfolio</span><span>คณะพาณิชยศาสตร์และการบัญชี มหาวิทยาลัยธรรมศาสตร์</span></footer>`;
