const p = window.PORTFOLIO;
const esc = s => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const routes = [['index.html','หน้าแรก'],['profile.html','ข้อมูลส่วนตัว'],['certificates.html','เกียรติบัตร'],['thanks.html','ขอบคุณ']];
const current = location.pathname.split('/').pop() || 'index.html';
const page = Math.max(0, routes.findIndex(r => r[0] === current));
const arrow = '<span aria-hidden="true">↗</span>';
const photo = p.portrait ? `<img class="portrait" src="${esc(p.portrait)}" alt="ภาพของ ${esc(p.name)}">` : '<div class="portrait-empty"><span class="portrait-monogram">rx.</span><span>พื้นที่สำหรับรูปของคุณ</span><small>MY PORTRAIT</small></div>';
const university = p.universityLogo ? `<div class="university-lockup"><img src="${esc(p.universityLogo)}" alt="ตรามหาวิทยาลัยธรรมศาสตร์"><div><span>เป้าหมายการศึกษาต่อ</span><strong>คณะพาณิชยศาสตร์และการบัญชี</strong><b>สาขาบริหารธุรกิจ</b><p>มหาวิทยาลัยธรรมศาสตร์</p></div></div>` : '';
const pages = [
`<section class="hero"><div class="hero-copy"><div class="eyebrow"><span class="short-line"></span> A JOURNEY TO BUSINESS ADMINISTRATION</div><h1 class="portfolio-title">PORTFOLIO<span class="portfolio-title-th blue">แฟ้มสะสมผลงาน</span></h1><p class="hero-sub">ก้าวแรกสู่การเรียนบริหาร<br>เริ่มต้นจากความใส่ใจ และความตั้งใจที่จะเรียนรู้</p><div class="applicant"><img class="applicant-school-logo" src="${esc(p.schoolLogo)}" alt="ตราโรงเรียนบ้านบึงอุตสาหกรรมนุเคราะห์"><div><strong>${esc(p.name)}</strong><p>${esc(p.school)}</p></div></div></div><div class="cover"><div class="cover-top"><span>MY PORTFOLIO</span><span>01 / 04</span></div><div class="cover-image cover-portrait"><img src="${esc(p.portrait)}" alt="ภาพบุคคลสำหรับแฟ้มสะสมผลงาน"></div><div class="cover-caption"><span>With purpose,<br><em>for a better future.</em></span><span class="cover-star" aria-hidden="true">✳</span></div><div class="cover-tag">BUSINESS ADMINISTRATION</div></div></section><section class="university-strip">${university}<span class="university-motto">With purpose, for a better future.</span></section><section class="preface"><div><div class="eyebrow">A LITTLE INTRODUCTION</div><h2>คำนำ</h2></div><div><p>${esc(p.introduction)}</p><span class="draft-note">ข้อความคำนำฉบับร่าง · ปรับให้เป็นเรื่องราวของคุณได้</span></div></section>`,
`<section class="page-heading"><div class="eyebrow">02 / ABOUT ME</div><h1>รู้จัก<span class="blue">ตัวฉัน</span></h1><p>ตัวตนในวันนี้ กับความตั้งใจในวันข้างหน้า</p></section><section class="profile-layout"><div class="profile-photo">${photo}<div class="photo-caption">${esc(p.englishName)}<span>ASPIRING BUSINESS LEADER</span></div></div><div class="profile-details"><h2>${esc(p.name)}</h2><p class="school-name">${esc(p.school)}</p><dl class="facts">${[['ชื่อเล่น',p.nickname],['ระดับชั้น',p.grade],['แผนการเรียน',p.program],['เกรดเฉลี่ยสะสม',p.gpa],['อีเมล',p.email]].map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><div class="aspiration">${university}</div></div></section><section class="preface"><div><div class="eyebrow">MY INTENTION</div><h2>เหตุผลที่อยาก<br>เรียนบริหาร</h2></div><div><p>${esc(p.motivation)}</p><span class="draft-note">ข้อความฉบับร่าง · เพิ่มแรงบันดาลใจจากประสบการณ์จริงของคุณ</span></div></section>`,
`<section class="page-heading"><div class="eyebrow">03 / CERTIFICATES</div><h1>ทุกการเรียนรู้<br>คือ<span class="blue">อีกก้าวของฉัน</span></h1><p>เกียรติบัตรและหลักฐานแห่งความตั้งใจ</p></section><section class="certificate-section"><div class="section-label"><h2>เกียรติบัตร</h2><span>${String(p.certificates.length).padStart(2,'0')} รายการ</span></div>${p.certificates.length ? `<div class="certificate-grid">${p.certificates.map((c,i)=>`<button class="certificate" data-index="${i}"><div class="certificate-image"><img src="${esc(c.image)}" alt="${esc(c.title)}"></div><div class="certificate-info"><span class="eyebrow">${esc(c.year)}</span><h3>${esc(c.title)}</h3><p>${esc(c.issuer)}</p><span class="view-label">ดูเกียรติบัตร ${arrow}</span></div></button>`).join('')}</div>` : '<div class="empty-cert"><span class="empty-number">03</span><div><h3>เรื่องราวความสำเร็จ กำลังจะเติมเต็มที่นี่</h3><p>ยังไม่มีเกียรติบัตรที่เพิ่มไว้</p><span class="draft-note">พื้นที่สำหรับผลงานและเกียรติบัตรจริงของคุณ</span></div></div>'}</section><dialog id="certificate-dialog"><button class="close-dialog" aria-label="ปิดภาพเกียรติบัตร">✕</button><img id="full-certificate" alt=""><p id="certificate-title"></p></dialog>`,
`<section class="thanks"><div class="eyebrow">04 / THANK YOU</div><span class="thanks-serif">Thank you.</span><h1>ขอบคุณที่เป็นส่วนหนึ่ง<br>ใน<span class="blue">ก้าวสำคัญของฉัน</span></h1><p>ขอขอบพระคุณคณะกรรมการทุกท่าน<br>ที่สละเวลาพิจารณาแฟ้มสะสมผลงานฉบับนี้</p><div class="thanks-signature"><strong>${esc(p.name)}</strong><span>${esc(p.school)}</span></div><a class="text-link" href="index.html">กลับสู่หน้าแรก <span aria-hidden="true">↗</span></a></section><div class="closing-band"><span>THE NEXT CHAPTER</span><p>คณะพาณิชยศาสตร์และการบัญชี <span>มหาวิทยาลัยธรรมศาสตร์</span></p><span aria-hidden="true">✳</span></div>`
];
document.title = `${routes[page][1]} · RXIN Portfolio`;
document.querySelector('#app').innerHTML = `<a class="skip" href="#main">ข้ามไปยังเนื้อหา</a><header class="site-header"><a class="brand" href="index.html" aria-label="RXIN Portfolio หน้าแรก">rxin<span class="brand-dot">.</span><span class="brand-description">STUDENT<br>PORTFOLIO</span></a><nav aria-label="เมนูหลัก">${routes.map(([url,label],i)=>`<a href="${url}" ${i===page?'aria-current="page"':''}><span class="nav-number">0${i+1}</span>${label}</a>`).join('')}</nav><div class="header-university"><img src="${esc(p.universityLogo)}" alt="ตรามหาวิทยาลัยธรรมศาสตร์"><span>BUSINESS<br>THAMMASAT</span></div></header><main id="main">${pages[page]}${page<3?`<div class="page-next"><span>0${page+1} — 04</span><a href="${routes[page+1][0]}">ถัดไป · ${routes[page+1][1]} <span aria-hidden="true">→</span></a></div>`:''}</main><footer><div class="footer-school">${p.schoolLogo?`<img src="${esc(p.schoolLogo)}" alt="ตราโรงเรียน">`:'<span class="school-mark" aria-hidden="true">B.</span>'}<span>${esc(p.school)}</span></div><span>แฟ้มสะสมผลงานเพื่อการศึกษาต่อ <span class="footer-dot">·</span> RXIN</span></footer>`;
const modal=document.querySelector('#certificate-dialog');
if(modal){document.querySelectorAll('[data-index]').forEach(b=>b.addEventListener('click',()=>{const c=p.certificates[Number(b.dataset.index)];const img=document.querySelector('#full-certificate');img.src=c.image;img.alt=c.title;document.querySelector('#certificate-title').textContent=c.title;modal.showModal();}));modal.querySelector('.close-dialog').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{if(e.target===modal)modal.close();});}
